python Example-iris-smoothing-logicbug.py /data1/zhaojing/regularization/uci-dataset/car_evaluation/car.categorical.data 1 1
python Example-iris-smoothing-logicbug.py /data1/zhaojing/regularization/uci-dataset/car_evaluation/car.categorical.data 1 0
python Example-iris-smoothing-logicbug.py /data1/zhaojing/regularization/uci-dataset/Audiology/audio_data/audiology.standardized.traintestcategorical.data 1 1
python Example-iris-smoothing-logicbug.py /data1/zhaojing/regularization/uci-dataset/Audiology/audio_data/audiology.standardized.traintestcategorical.data 1 0
python Example-iris-smoothing-logicbug.py /data1/zhaojing/regularization/uci-dataset/balance_scale/balance-scale.categorical.data 0 1
python Example-iris-smoothing-logicbug.py /data1/zhaojing/regularization/uci-dataset/balance_scale/balance-scale.categorical.data 0 0
python Example-iris-smoothing-logicbug.py /data1/zhaojing/regularization/uci-dataset/dermatology/dermatology.categorical.csv 1 1
python Example-iris-smoothing-logicbug.py /data1/zhaojing/regularization/uci-dataset/dermatology/dermatology.categorical.csv 1 0
python Example-iris-smoothing-logicbug.py /data1/zhaojing/regularization/uci-dataset/congression/house-votes-84.categorical.data 0 1
python Example-iris-smoothing-logicbug.py /data1/zhaojing/regularization/uci-dataset/congression/house-votes-84.categorical.data 0 0
python Example-iris-smoothing-logicbug.py /data1/zhaojing/regularization/uci-dataset/car_evaluation/car.categorical.data 1 1
python Example-iris-smoothing-logicbug.py /data1/zhaojing/regularization/uci-dataset/car_evaluation/car.categorical.data 1 0
python Example-iris-smoothing-logicbug.py /data1/zhaojing/regularization/uci-dataset/Audiology/audio_data/audiology.standardized.traintestcategorical.data 1 1
python Example-iris-smoothing-logicbug.py /data1/zhaojing/regularization/uci-dataset/Audiology/audio_data/audiology.standardized.traintestcategorical.data 1 0
python Example-iris-smoothing-logicbug.py /data1/zhaojing/regularization/uci-dataset/balance_scale/balance-scale.categorical.data 0 1
python Example-iris-smoothing-logicbug.py /data1/zhaojing/regularization/uci-dataset/balance_scale/balance-scale.categorical.data 0 0
python Example-iris-smoothing-logicbug.py /data1/zhaojing/regularization/uci-dataset/dermatology/dermatology.categorical.csv 1 1
python Example-iris-smoothing-logicbug.py /data1/zhaojing/regularization/uci-dataset/dermatology/dermatology.categorical.csv 1 0
python Example-iris-smoothing-logicbug.py /data1/zhaojing/regularization/uci-dataset/congression/house-votes-84.categorical.data 0 1
python Example-iris-smoothing-logicbug.py /data1/zhaojing/regularization/uci-dataset/congression/house-votes-84.categorical.data 0 0