# LR = 1e-7, 1 epoch, only test time
python gm_prior_logistic_regression_URL_best.py -datapath /data/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 7 -pirlr 7 -lambdaslr 7 -maxiter 50 -gmnum 4 -gmoptmethod 2 | tee -a /data/zhaojing/regularization/log180908/tkde-URL-1-epoch/tkde-URL-1-epoch-7.log
python gm_prior_logistic_regression_URL_best.py -datapath /data/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 7 -pirlr 7 -lambdaslr 7 -maxiter 100 -gmnum 4 -gmoptmethod 2 | tee -a /data/zhaojing/regularization/log180908/tkde-URL-1-epoch/tkde-URL-1-epoch-8.log
python lasso_logistic_regression_URL_best.py -datapath /data/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 7 -maxiter 5000 | tee -a /data/zhaojing/regularization/log180908/tkde-URL-1-epoch/tkde-URL-1-epoch-1.log
python logistic_regression_URL_best.py -datapath /data/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 7 -maxiter 5000 | tee -a /data/zhaojing/regularization/log180908/tkde-URL-1-epoch/tkde-URL-1-epoch-2.log
python elasticnet_logistic_regression_URL_best.py -datapath /data/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 7 -maxiter 5000 | tee -a /data/zhaojing/regularization/log180908/tkde-URL-1-epoch/tkde-URL-1-epoch-3.log
python huber_one_weight_logistic_regression_URL_best.py -datapath /data/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 7 -maxiter 5000 | tee -a /data/zhaojing/regularization/log180908/tkde-URL-1-epoch/tkde-URL-1-epoch-4.log
python huber_logistic_regression_URL_best.py -datapath /data/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 7 -maxiter 5000 | tee -a /data/zhaojing/regularization/log180908/tkde-URL-1-epoch/tkde-URL-1-epoch-5.log
python gm_prior_logistic_regression_sparse_URL_best.py -datapath /data/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 7 -pirlr 7 -lambdaslr 7 -maxiter 5000 -gmmuptfreq 100 -gmnum 4 -gmoptmethod 2 | tee -a /data/zhaojing/regularization/log180908/tkde-URL-1-epoch/tkde-URL-1-epoch-6.log
python gm_prior_logistic_regression_URL_best.py -datapath /data/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 7 -pirlr 7 -lambdaslr 7 -maxiter 50 -gmnum 4 -gmoptmethod 2 | tee -a /data/zhaojing/regularization/log180908/tkde-URL-1-epoch/tkde-URL-1-epoch-7.log
python gm_prior_logistic_regression_URL_best.py -datapath /data/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 7 -pirlr 7 -lambdaslr 7 -maxiter 100 -gmnum 4 -gmoptmethod 2 | tee -a /data/zhaojing/regularization/log180908/tkde-URL-1-epoch/tkde-URL-1-epoch-8.log
python lasso_logistic_regression_URL_best.py -datapath /data/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 7 -maxiter 5000 | tee -a /data/zhaojing/regularization/log180908/tkde-URL-1-epoch/tkde-URL-1-epoch-1.log
python logistic_regression_URL_best.py -datapath /data/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 7 -maxiter 5000 | tee -a /data/zhaojing/regularization/log180908/tkde-URL-1-epoch/tkde-URL-1-epoch-2.log
python elasticnet_logistic_regression_URL_best.py -datapath /data/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 7 -maxiter 5000 | tee -a /data/zhaojing/regularization/log180908/tkde-URL-1-epoch/tkde-URL-1-epoch-3.log
python huber_one_weight_logistic_regression_URL_best.py -datapath /data/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 7 -maxiter 5000 | tee -a /data/zhaojing/regularization/log180908/tkde-URL-1-epoch/tkde-URL-1-epoch-4.log
python huber_logistic_regression_URL_best.py -datapath /data/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 7 -maxiter 5000 | tee -a /data/zhaojing/regularization/log180908/tkde-URL-1-epoch/tkde-URL-1-epoch-5.log
python gm_prior_logistic_regression_sparse_URL_best.py -datapath /data/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 7 -pirlr 7 -lambdaslr 7 -maxiter 5000 -gmmuptfreq 100 -gmnum 4 -gmoptmethod 2 | tee -a /data/zhaojing/regularization/log180908/tkde-URL-1-epoch/tkde-URL-1-epoch-6.log
python gm_prior_logistic_regression_URL_best.py -datapath /data/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 7 -pirlr 7 -lambdaslr 7 -maxiter 50 -gmnum 4 -gmoptmethod 2 | tee -a /data/zhaojing/regularization/log180908/tkde-URL-1-epoch/tkde-URL-1-epoch-7.log
python gm_prior_logistic_regression_URL_best.py -datapath /data/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 7 -pirlr 7 -lambdaslr 7 -maxiter 100 -gmnum 4 -gmoptmethod 2 | tee -a /data/zhaojing/regularization/log180908/tkde-URL-1-epoch/tkde-URL-1-epoch-8.log
