python gm_prior_logistic_regression.py -datapath data/LACE-CNN-1500-lastcase.pkl -onehot 0 -sparsify 0 -batchsize 50 -wlr 4 -pirlr 4 -lambdaslr 4 -maxiter 50000 -gmnum 4 -gmoptmethod 1 | tee -a /data/zhaojing/regularization/log0408/test-loss/test-loss-1
python gm_prior_logistic_regression.py -datapath data/LACE-CNN-1500-lastcase.pkl -onehot 0 -sparsify 0 -batchsize 50 -wlr 4 -pirlr 4 -lambdaslr 4 -maxiter 50000 -gmnum 4 -gmoptmethod 2 | tee -a /data/zhaojing/regularization/log0408/test-loss/test-loss-2
python lasso_logistic_regression.py -datapath data/LACE-CNN-1500-lastcase.pkl -onehot 0 -sparsify 0 -batchsize 50 -wlr 4 -maxiter 30000 | tee -a /data/zhaojing/regularization/log0408/test-loss/test-loss-3
python logistic_regression.py -datapath data/LACE-CNN-1500-lastcase.pkl -onehot 0 -sparsify 0 -batchsize 50 -wlr 4 -maxiter 30000 | tee -a /data/zhaojing/regularization/log0408/test-loss/test-loss-4
python elasticnet_logistic_regression.py -datapath data/LACE-CNN-1500-lastcase.pkl -onehot 0 -sparsify 0 -batchsize 50 -wlr 4 -maxiter 30000 | tee -a /data/zhaojing/regularization/log0408/test-loss/test-loss-5
python huber_logistic_regression.py -datapath data/LACE-CNN-1500-lastcase.pkl -onehot 0 -sparsify 0 -batchsize 50 -wlr 4 -maxiter 30000 | tee -a /data/zhaojing/regularization/log0408/test-loss/test-loss-6

python gm_prior_logistic_regression.py -datapath data/simulator.pkl -onehot 0 -sparsify 0 -batchsize 500 -wlr 4 -pirlr 4 -lambdaslr 4 -maxiter 300000 -gmnum 4 -gmoptmethod 1 | tee -a /data/zhaojing/regularization/log0408/test-loss/test-loss-7
python gm_prior_logistic_regression.py -datapath data/simulator.pkl -onehot 0 -sparsify 0 -batchsize 500 -wlr 4 -pirlr 4 -lambdaslr 4 -maxiter 300000 -gmnum 4 -gmoptmethod 2 | tee -a /data/zhaojing/regularization/log0408/test-loss/test-loss-8
python lasso_logistic_regression.py -datapath data/simulator.pkl -onehot 0 -sparsify 0 -batchsize 500 -wlr 4 -maxiter 50000 | tee -a /data/zhaojing/regularization/log0408/test-loss/test-loss-9
python logistic_regression.py -datapath data/simulator.pkl -onehot 0 -sparsify 0 -batchsize 500 -wlr 4 -maxiter 50000 | tee -a /data/zhaojing/regularization/log0408/test-loss/test-loss-10
python elasticnet_logistic_regression.py -datapath data/simulator.pkl -onehot 0 -sparsify 0 -batchsize 500 -wlr 4 -maxiter 50000 | tee -a /data/zhaojing/regularization/log0408/test-loss/test-loss-11
python huber_logistic_regression.py -datapath data/simulator.pkl -onehot 0 -sparsify 0 -batchsize 500 -wlr 4 -maxiter 50000 | tee -a /data/zhaojing/regularization/log0408/test-loss/test-loss-12

python gm_prior_logistic_regression.py -datapath data/diabetic_data_diag_low_dim_2_class_categorical.pkl -onehot 1 -sparsify 0 -batchsize 500 -wlr 4 -pirlr 4 -lambdaslr 4 -maxiter 1000000 -gmnum 4 -gmoptmethod 1 | tee -a /data/zhaojing/regularization/log0408/test-loss/test-loss-13
python gm_prior_logistic_regression.py -datapath data/diabetic_data_diag_low_dim_2_class_categorical.pkl -onehot 1 -sparsify 0 -batchsize 500 -wlr 4 -pirlr 4 -lambdaslr 4 -maxiter 1000000 -gmnum 4 -gmoptmethod 2 | tee -a /data/zhaojing/regularization/log0408/test-loss/test-loss-14
python lasso_logistic_regression.py -datapath data/diabetic_data_diag_low_dim_2_class_categorical.pkl -onehot 1 -sparsify 0 -batchsize 500 -wlr 4 -maxiter 300000 | tee -a /data/zhaojing/regularization/log0408/test-loss/test-loss-15
python logistic_regression.py -datapath data/diabetic_data_diag_low_dim_2_class_categorical.pkl -onehot 1 -sparsify 0 -batchsize 500 -wlr 4 -maxiter 300000 | tee -a /data/zhaojing/regularization/log0408/test-loss/test-loss-16
python elasticnet_logistic_regression.py -datapath data/diabetic_data_diag_low_dim_2_class_categorical.pkl -onehot 1 -sparsify 0 -batchsize 500 -wlr 4 -maxiter 300000 | tee -a /data/zhaojing/regularization/log0408/test-loss/test-loss-17
python huber_logistic_regression.py -datapath data/diabetic_data_diag_low_dim_2_class_categorical.pkl -onehot 1 -sparsify 0 -batchsize 500 -wlr 4 -maxiter 300000 | tee -a /data/zhaojing/regularization/log0408/test-loss/test-loss-18

python lasso_logistic_regression_URL_best.py -datapath /data/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 6 -maxiter 50000 | tee -a /data/zhaojing/regularization/log0408/test-loss/test-loss-19
python logistic_regression_URL_best.py -datapath /data/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -maxiter 50000 | tee -a /data/zhaojing/regularization/log0408/test-loss/test-loss-20
python elasticnet_logistic_regression_URL_best.py -datapath /data/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 6 -maxiter 50000 | tee -a /data/zhaojing/regularization/log0408/test-loss/test-loss-21
python huber_logistic_regression_URL_best.py -datapath /data/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 6 -maxiter 50000 | tee -a /data/zhaojing/regularization/log0408/test-loss/test-loss-22

python gm_prior_logistic_regression_sparse_URL_best_1.py -datapath /data0/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -pirlr 6 -lambdaslr 6 -maxiter 50000 -gmmuptfreq 100 -gmnum 4 -gmoptmethod 1 | tee -a /data0/zhaojing/regularization/log0408/test-loss/test-loss-23
python gm_prior_logistic_regression_sparse_URL_best_2.py -datapath /data0/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -pirlr 6 -lambdaslr 6 -maxiter 50000 -gmmuptfreq 100 -gmnum 4 -gmoptmethod 1 | tee -a /data0/zhaojing/regularization/log0408/test-loss/test-loss-24
python gm_prior_logistic_regression_sparse_URL_best_1.py -datapath /data/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -pirlr 7 -lambdaslr 7 -maxiter 50000 -gmmuptfreq 100 -gmnum 4 -gmoptmethod 1 | tee -a /data/zhaojing/regularization/log0408/test-loss/test-loss-25
python gm_prior_logistic_regression_sparse_URL_best_2.py -datapath /data/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -pirlr 7 -lambdaslr 7 -maxiter 50000 -gmmuptfreq 100 -gmnum 4 -gmoptmethod 1 | tee -a /data/zhaojing/regularization/log0408/test-loss/test-loss-26
python gm_prior_logistic_regression_sparse_URL_best_1.py -datapath /data/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -pirlr 8 -lambdaslr 8 -maxiter 50000 -gmmuptfreq 100 -gmnum 4 -gmoptmethod 1 | tee -a /data/zhaojing/regularization/log0408/test-loss/test-loss-27
python gm_prior_logistic_regression_sparse_URL_best_2.py -datapath /data/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -pirlr 8 -lambdaslr 8 -maxiter 50000 -gmmuptfreq 100 -gmnum 4 -gmoptmethod 1 | tee -a /data/zhaojing/regularization/log0408/test-loss/test-loss-28

python gm_prior_logistic_regression_URL_best.py -datapath /data/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -pirlr 8 -lambdaslr 8 -maxiter 50000 -gmnum 4 -gmoptmethod 1 | tee -a /data/zhaojing/regularization/log0408/test-loss/test-loss-29
python gm_prior_logistic_regression_URL_best.py -datapath /data/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -pirlr 8 -lambdaslr 8 -maxiter 50000 -gmnum 4 -gmoptmethod 2 | tee -a /data/zhaojing/regularization/log0408/test-loss/test-loss-30