#total iterations is 12500 only
#sesame-1
python gm_prior_logistic_regression_sparse_URL_best_1_1.py -datapath /data/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -pirlr 8 -lambdaslr 8 -maxiter 12500 -gmmuptfreq 100 -gmnum 4 -gmoptmethod 2 | tee -a /data/zhaojing/regularization/log0411/test-loss-EM/test-loss-EM-1.log
python gm_prior_logistic_regression_sparse_URL_best_1_2.py -datapath /data/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -pirlr 8 -lambdaslr 8 -maxiter 12500 -gmmuptfreq 100 -gmnum 4 -gmoptmethod 2 | tee -a /data/zhaojing/regularization/log0411/test-loss-EM/test-loss-EM-2.log
python gm_prior_logistic_regression_sparse_URL_best_1_3.py -datapath /data/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -pirlr 8 -lambdaslr 8 -maxiter 12500 -gmmuptfreq 100 -gmnum 4 -gmoptmethod 2 | tee -a /data/zhaojing/regularization/log0411/test-loss-EM/test-loss-EM-3.log
#sesame-3
python gm_prior_logistic_regression_sparse_URL_best_2_1.py -datapath /data/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -pirlr 8 -lambdaslr 8 -maxiter 12500 -gmmuptfreq 100 -gmnum 4 -gmoptmethod 2 | tee -a /data/zhaojing/regularization/log0411/test-loss-EM/test-loss-EM-4.log
python gm_prior_logistic_regression_sparse_URL_best_2_2.py -datapath /data/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -pirlr 8 -lambdaslr 8 -maxiter 12500 -gmmuptfreq 100 -gmnum 4 -gmoptmethod 2 | tee -a /data/zhaojing/regularization/log0411/test-loss-EM/test-loss-EM-5.log
python gm_prior_logistic_regression_sparse_URL_best_2_3.py -datapath /data/zhaojing/regularization/url-dataset/url_svmlight_merge/Day_0_120.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -pirlr 8 -lambdaslr 8 -maxiter 12500 -gmmuptfreq 100 -gmnum 4 -gmoptmethod 2 | tee -a /data/zhaojing/regularization/log0411/test-loss-EM/test-loss-EM-6.log

python gm_prior_logistic_regression_a_b_all.py -datapath data/LACE-CNN-1500-lastcase.pkl -onehot 0 -sparsify 0 -batchsize 50 -wlr 4 -pirlr 4 -lambdaslr 4 -maxiter 50000 -gmnum 4 -gmoptmethod 2 | tee -a /data/zhaojing/regularization/log0411/test-loss-EM/test-loss-EM-7.log
python gm_prior_logistic_regression_a_b_all_1.py -datapath data/diabetic_data_diag_low_dim_2_class_categorical.pkl -onehot 1 -sparsify 0 -batchsize 500 -wlr 4 -pirlr 4 -lambdaslr 4 -maxiter 1000000 -gmnum 4 -gmoptmethod 2 | tee -a /data/zhaojing/regularization/log0411/test-loss-EM/test-loss-EM-8.log
python gm_prior_logistic_regression_a_b_all_2.py -datapath data/diabetic_data_diag_low_dim_2_class_categorical.pkl -onehot 1 -sparsify 0 -batchsize 500 -wlr 4 -pirlr 4 -lambdaslr 4 -maxiter 1000000 -gmnum 4 -gmoptmethod 2 | tee -a /data/zhaojing/regularization/log0411/test-loss-EM/test-loss-EM-9.log