python lasso_logistic_regression_svm.py -datapath /data/zhaojing/regularization/webspam/webspam_train_50000.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -maxiter 9000 | tee -a /data/zhaojing/regularization/log0424/webspam/webspam-1
python logistic_regression_svm.py -datapath /data/zhaojing/regularization/webspam/webspam_train_50000.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -maxiter 9000 | tee -a /data/zhaojing/regularization/log0424/webspam/webspam-2

python elasticnet_logistic_regression_svm_1.py -datapath /data/zhaojing/regularization/webspam/webspam_train_50000.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -maxiter 9000 | tee -a /data/zhaojing/regularization/log0424/webspam/webspam-3
python elasticnet_logistic_regression_svm_2.py -datapath /data/zhaojing/regularization/webspam/webspam_train_50000.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -maxiter 9000 | tee -a /data/zhaojing/regularization/log0424/webspam/webspam-4
python elasticnet_logistic_regression_svm_3.py -datapath /data/zhaojing/regularization/webspam/webspam_train_50000.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -maxiter 9000 | tee -a /data/zhaojing/regularization/log0424/webspam/webspam-5

python elasticnet_logistic_regression_svm_4.py -datapath /data/zhaojing/regularization/webspam/webspam_train_50000.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -maxiter 9000 | tee -a /data/zhaojing/regularization/log0424/webspam/webspam-6
python elasticnet_logistic_regression_svm_5.py -datapath /data/zhaojing/regularization/webspam/webspam_train_50000.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -maxiter 9000 | tee -a /data/zhaojing/regularization/log0424/webspam/webspam-7

python huber_one_weight_logistic_regression_svm_1.py -datapath /data/zhaojing/regularization/webspam/webspam_train_50000.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -maxiter 9000 | tee -a /data/zhaojing/regularization/log0424/webspam/webspam-8
python huber_one_weight_logistic_regression_svm_2.py -datapath /data/zhaojing/regularization/webspam/webspam_train_50000.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -maxiter 9000 | tee -a /data/zhaojing/regularization/log0424/webspam/webspam-9

python huber_one_weight_logistic_regression_svm_3.py -datapath /data/zhaojing/regularization/webspam/webspam_train_50000.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -maxiter 9000 | tee -a /data/zhaojing/regularization/log0424/webspam/webspam-10
python huber_one_weight_logistic_regression_svm_4.py -datapath /data/zhaojing/regularization/webspam/webspam_train_50000.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -maxiter 9000 | tee -a /data/zhaojing/regularization/log0424/webspam/webspam-11

python huber_one_weight_logistic_regression_svm_5.py -datapath /data/zhaojing/regularization/webspam/webspam_train_50000.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -maxiter 9000 | tee -a /data/zhaojing/regularization/log0424/webspam/webspam-12
python huber_one_weight_logistic_regression_svm_6.py -datapath /data/zhaojing/regularization/webspam/webspam_train_50000.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -maxiter 9000 | tee -a /data/zhaojing/regularization/log0424/webspam/webspam-13
python huber_one_weight_logistic_regression_svm_7.py -datapath /data/zhaojing/regularization/webspam/webspam_train_50000.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -maxiter 9000 | tee -a /data/zhaojing/regularization/log0424/webspam/webspam-14
python huber_one_weight_logistic_regression_svm_8.py -datapath /data/zhaojing/regularization/webspam/webspam_train_50000.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -maxiter 9000 | tee -a /data/zhaojing/regularization/log0424/webspam/webspam-15

python gm_prior_logistic_regression_sparse_svm_8.py -datapath /data/zhaojing/regularization/webspam/webspam_train_50000.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -pirlr 5 -lambdaslr 5 -maxiter 9000 -gmmuptfreq 100 -gmnum 4 -gmoptmethod 1 | tee -a /data/zhaojing/regularization/log0424/webspam/webspam-16
python gm_prior_logistic_regression_sparse_svm_7.py -datapath /data/zhaojing/regularization/webspam/webspam_train_50000.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -pirlr 5 -lambdaslr 5 -maxiter 9000 -gmmuptfreq 100 -gmnum 4 -gmoptmethod 1 | tee -a /data/zhaojing/regularization/log0424/webspam/webspam-17
python gm_prior_logistic_regression_sparse_svm_6.py -datapath /data/zhaojing/regularization/webspam/webspam_train_50000.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -pirlr 5 -lambdaslr 5 -maxiter 9000 -gmmuptfreq 100 -gmnum 4 -gmoptmethod 1 | tee -a /data/zhaojing/regularization/log0424/webspam/webspam-18
python gm_prior_logistic_regression_sparse_svm_5.py -datapath /data/zhaojing/regularization/webspam/webspam_train_50000.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -pirlr 5 -lambdaslr 5 -maxiter 9000 -gmmuptfreq 100 -gmnum 4 -gmoptmethod 1 | tee -a /data/zhaojing/regularization/log0424/webspam/webspam-19
python gm_prior_logistic_regression_sparse_svm_4.py -datapath /data/zhaojing/regularization/webspam/webspam_train_50000.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -pirlr 5 -lambdaslr 5 -maxiter 9000 -gmmuptfreq 100 -gmnum 4 -gmoptmethod 1 | tee -a /data/zhaojing/regularization/log0424/webspam/webspam-20
python gm_prior_logistic_regression_sparse_svm_3.py -datapath /data/zhaojing/regularization/webspam/webspam_train_50000.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -pirlr 5 -lambdaslr 5 -maxiter 9000 -gmmuptfreq 100 -gmnum 4 -gmoptmethod 1 | tee -a /data/zhaojing/regularization/log0424/webspam/webspam-21

python gm_prior_logistic_regression_sparse_svm_2.py -datapath /data/zhaojing/regularization/webspam/webspam_train_50000.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -pirlr 5 -lambdaslr 5 -maxiter 9000 -gmmuptfreq 100 -gmnum 4 -gmoptmethod 1 | tee -a /data/zhaojing/regularization/log0424/webspam/webspam-22
python gm_prior_logistic_regression_sparse_svm_1.py -datapath /data/zhaojing/regularization/webspam/webspam_train_50000.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -pirlr 5 -lambdaslr 5 -maxiter 9000 -gmmuptfreq 100 -gmnum 4 -gmoptmethod 1 | tee -a /data/zhaojing/regularization/log0424/webspam/webspam-23
python gm_prior_logistic_regression_sparse_svm_8.py -datapath /data/zhaojing/regularization/webspam/webspam_train_50000.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -pirlr 5 -lambdaslr 5 -maxiter 9000 -gmmuptfreq 100 -gmnum 4 -gmoptmethod 2 | tee -a /data/zhaojing/regularization/log0424/webspam/webspam-24
python gm_prior_logistic_regression_sparse_svm_7.py -datapath /data/zhaojing/regularization/webspam/webspam_train_50000.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -pirlr 5 -lambdaslr 5 -maxiter 9000 -gmmuptfreq 100 -gmnum 4 -gmoptmethod 2 | tee -a /data/zhaojing/regularization/log0424/webspam/webspam-25
python gm_prior_logistic_regression_sparse_svm_6.py -datapath /data/zhaojing/regularization/webspam/webspam_train_50000.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -pirlr 5 -lambdaslr 5 -maxiter 9000 -gmmuptfreq 100 -gmnum 4 -gmoptmethod 2 | tee -a /data/zhaojing/regularization/log0424/webspam/webspam-26
python gm_prior_logistic_regression_sparse_svm_5.py -datapath /data/zhaojing/regularization/webspam/webspam_train_50000.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -pirlr 5 -lambdaslr 5 -maxiter 9000 -gmmuptfreq 100 -gmnum 4 -gmoptmethod 2 | tee -a /data/zhaojing/regularization/log0424/webspam/webspam-27
python gm_prior_logistic_regression_sparse_svm_4.py -datapath /data/zhaojing/regularization/webspam/webspam_train_50000.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -pirlr 5 -lambdaslr 5 -maxiter 9000 -gmmuptfreq 100 -gmnum 4 -gmoptmethod 2 | tee -a /data/zhaojing/regularization/log0424/webspam/webspam-28
python gm_prior_logistic_regression_sparse_svm_3.py -datapath /data/zhaojing/regularization/webspam/webspam_train_50000.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -pirlr 5 -lambdaslr 5 -maxiter 9000 -gmmuptfreq 100 -gmnum 4 -gmoptmethod 2 | tee -a /data/zhaojing/regularization/log0424/webspam/webspam-29
python gm_prior_logistic_regression_sparse_svm_2.py -datapath /data/zhaojing/regularization/webspam/webspam_train_50000.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -pirlr 5 -lambdaslr 5 -maxiter 9000 -gmmuptfreq 100 -gmnum 4 -gmoptmethod 2 | tee -a /data/zhaojing/regularization/log0424/webspam/webspam-30
python gm_prior_logistic_regression_sparse_svm_1.py -datapath /data/zhaojing/regularization/webspam/webspam_train_50000.svm -onehot 0 -sparsify 1 -batchsize 500 -wlr 5 -pirlr 5 -lambdaslr 5 -maxiter 9000 -gmmuptfreq 100 -gmnum 4 -gmoptmethod 2 | tee -a /data/zhaojing/regularization/log0424/webspam/webspam-31